### ISSUE TITLE
npm run start fails on a fresh clone

### ISSUE THREAD

**Issue by Mikearaya** [unchainedshop/currybag-website#8]
after cloning the repository and installing all the dependency inside storefront, i tried running `npm run start` but it failes with the following error 
![Screenshot from 2020-04-12 19-27-55](https://user-images.githubusercontent.com/9751246/79220422-a0516000-7e5c-11ea-954b-5c4ffd90b13e.png)

### I'm running 
- Ubuntu 19.04
- npm 6.14.4
- node 12

**Comment by schmidsi** [comment]
Hi @Mikearaya, thanks for opening this issue. It should be working now. Can you please pull, try again and confirm?

**Comment by schmidsi** [comment]
This should help to get you started: https://github.com/unchainedshop/currybag-website/blob/master/storefront/README.md

**Comment by Mikearaya** [comment]
yes that solved it, Thanks
